# Generated by Django 4.2.13 on 2026-05-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('specialization', models.CharField(max_length=150, verbose_name='Спеціалізація')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('experience', models.IntegerField(default=0, verbose_name='Досвід (роки)')),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Пацієнт',
                'verbose_name_plural': 'Пацієнти',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Дата та час прийому')),
                ('description', models.TextField(blank=True, verbose_name='Опис / скарги')),
                ('status', models.CharField(choices=[('planned', 'Заплановано'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='planned', max_length=20, verbose_name='Статус')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dental.doctor', verbose_name='Лікар')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dental.patient', verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Прийом',
                'verbose_name_plural': 'Прийоми',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
